<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>own_ship</name>
  <version>0.0.0</version>
  <description>Own Ship GNC & Collision Avoidance package</description>
  <maintainer email="lars@todo.todo">lars</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>maritime_interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>